services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: managertools
      POSTGRES_USER: managertools
      POSTGRES_PASSWORD: managertools
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
